

# This file was *autogenerated* from the file dlpwai.sage
from sage.all_cmdline import *   # import sage library

_sage_const_36313 = Integer(36313); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10)
p = _sage_const_36313 

G = GF(p)
g = G.gen()

k = divisors(p-_sage_const_1 )
print(k)
d = k[_sage_const_10 ]

